// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangeFeedPasswordData, ChangeFeedPasswordErrors, ChangeFeedPasswordResponses, DeleteFeedData, DeleteFeedErrors, DeleteFeedResponses, DeleteNoteData, DeleteNoteErrors, DeleteNoteResponses, EditNoteData, EditNoteErrors, EditNoteResponses, GetFeedData, GetFeedErrors, GetFeedResponses, GetNoteData, GetNoteErrors, GetNoteResponses, GetOpenApiData, GetOpenApiResponses, GetReadFeedData, GetReadFeedErrors, GetReadFeedResponses, GetReadNoteData, GetReadNoteErrors, GetReadNoteResponses, ListNotesData, ListNotesErrors, ListNotesResponses, ListReadNotesData, ListReadNotesErrors, ListReadNotesResponses, PostNoteData, PostNoteErrors, PostNoteResponses, RemoveFeedPasswordData, RemoveFeedPasswordErrors, RemoveFeedPasswordResponses, UpdateFeedData, UpdateFeedErrors, UpdateFeedResponses, UploadImageData, UploadImageErrors, UploadImageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List a feed's notes
 *
 * Newest first. A feed with no notes (or that doesn't exist yet) is an empty list.
 */
export const listNotes = <ThrowOnError extends boolean = false>(options: Options<ListNotesData, ThrowOnError>): RequestResult<ListNotesResponses, ListNotesErrors, ThrowOnError> => (options.client ?? client).get<ListNotesResponses, ListNotesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/notes',
    ...options
});

/**
 * Post a note
 *
 * Creates the feed with its first note, optionally protected by its own password (`X-Feed-Password` header or a `password` field in the JSON or form body; 1 to 256 printable ASCII characters, with no space at the start or end). Posting to a protected feed needs that password. Also served at `POST /{feed}`, the short form the client packages and curl one-liners use. The body is at most 102400 bytes and must be UTF-8. `application/x-www-form-urlencoded` (what `curl -d` sends) is read as raw markdown, not as form fields. Tags (at most 10 tags, each 1 to 32 characters of letters, digits, `-`, `_`, `.` and `:`; case is folded to lowercase, duplicates are removed) go in the JSON `tags` array, a repeated `tags` form field, or, for a raw body, the `X-Note-Tags` header.
 */
export const postNote = <ThrowOnError extends boolean = false>(options: Options<PostNoteData, ThrowOnError>): RequestResult<PostNoteResponses, PostNoteErrors, ThrowOnError> => (options.client ?? client).post<PostNoteResponses, PostNoteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a note
 *
 * Needs the feed's password if it has one, and counts against the post rate limit. The feed stays, even with no notes left. Read links can't delete.
 */
export const deleteNote = <ThrowOnError extends boolean = false>(options: Options<DeleteNoteData, ThrowOnError>): RequestResult<DeleteNoteResponses, DeleteNoteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteNoteResponses, DeleteNoteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/notes/{id}',
    ...options
});

/**
 * Get one note
 */
export const getNote = <ThrowOnError extends boolean = false>(options: Options<GetNoteData, ThrowOnError>): RequestResult<GetNoteResponses, GetNoteErrors, ThrowOnError> => (options.client ?? client).get<GetNoteResponses, GetNoteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/notes/{id}',
    ...options
});

/**
 * Edit a note
 *
 * Replaces the note's markdown; its id and creation time stay, the title follows the new text. Needs the feed's password if it has one, and counts against the post rate limit. Read links can't edit. The body is as for posting: at most 102400 bytes, UTF-8, a `password` field is ignored.
 */
export const editNote = <ThrowOnError extends boolean = false>(options: Options<EditNoteData, ThrowOnError>): RequestResult<EditNoteResponses, EditNoteErrors, ThrowOnError> => (options.client ?? client).put<EditNoteResponses, EditNoteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/notes/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload an image
 *
 * The body is the image itself: PNG, JPEG, GIF or WebP, recognized by its first bytes, whatever `Content-Type` is sent (SVG is refused). Stored byte-for-byte, with no resizing and no metadata stripped (EXIF such as GPS position stays in the file), as the first 32 hex characters of its SHA-256 plus an extension: the same bytes always give the same URL. The URL is under the feed's read id, so it works in the feed page, the read-only view and RSS readers without any password. Needs the same credentials as posting and counts against the post rate limit. The feed must exist: it is created by its first note. The size limit is NOTEFEED_MAX_IMAGE_BYTES (default 5 MiB); images deleted only with the feed.
 */
export const uploadImage = <ThrowOnError extends boolean = false>(options: Options<UploadImageData, ThrowOnError>): RequestResult<UploadImageResponses, UploadImageErrors, ThrowOnError> => (options.client ?? client).post<UploadImageResponses, UploadImageErrors, ThrowOnError>({
    bodySerializer: null,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/images',
    ...options,
    headers: {
        'Content-Type': 'image/png',
        ...options.headers
    }
});

/**
 * Delete a feed
 *
 * Deletes the feed with all its notes, its settings, its password and its read link, for good: there is no undo. The name is free again; a feed created there later gets a new read link, and the old one answers like an unknown one. Needs the feed's password if it has one, and counts against the post rate limit.
 */
export const deleteFeed = <ThrowOnError extends boolean = false>(options: Options<DeleteFeedData, ThrowOnError>): RequestResult<DeleteFeedResponses, DeleteFeedErrors, ThrowOnError> => (options.client ?? client).delete<DeleteFeedResponses, DeleteFeedErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}',
    ...options
});

/**
 * Get a feed's settings
 *
 * The title and description, the title image, whether the feed is protected, and its read link (null while it has no notes). A feed exists once its first note is posted.
 */
export const getFeed = <ThrowOnError extends boolean = false>(options: Options<GetFeedData, ThrowOnError>): RequestResult<GetFeedResponses, GetFeedErrors, ThrowOnError> => (options.client ?? client).get<GetFeedResponses, GetFeedErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}',
    ...options
});

/**
 * Change a feed's settings
 *
 * Replaces both the title (at most 100 characters) and the description (at most 500); surrounding whitespace is trimmed and control characters are refused. `show_sender` (default true) shows who posted each note to readers; omitted leaves it as it is. `image` is the file name `uploadImage` returned for this feed (title image), empty to remove it, or omitted to leave it as it is; any other value is a 400. `name` renames the feed and `read_id` gives it another read link (empty for a random one); the old name and the old read id are retired and answer 404 from then on, and the response is the feed under its new name. Both are capabilities on an open feed, so a short readable one is guessable: protect the feed with a password if that matters. An instance can turn chosen names and read ids off (NOTEFEED_ALLOW_CUSTOM_IDS=0): then only an empty `read_id` is accepted. Needs the feed's password if it has one, and counts against the post rate limit. Only on a feed that exists: it is created by its first note. Read links can't change settings.
 */
export const updateFeed = <ThrowOnError extends boolean = false>(options: Options<UpdateFeedData, ThrowOnError>): RequestResult<UpdateFeedResponses, UpdateFeedErrors, ThrowOnError> => (options.client ?? client).put<UpdateFeedResponses, UpdateFeedErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a feed's password
 *
 * Needs the current password in `X-Feed-Password`. The feed stays, open to anyone who knows its name. An open feed answers 409.
 */
export const removeFeedPassword = <ThrowOnError extends boolean = false>(options: Options<RemoveFeedPasswordData, ThrowOnError>): RequestResult<RemoveFeedPasswordResponses, RemoveFeedPasswordErrors, ThrowOnError> => (options.client ?? client).delete<RemoveFeedPasswordResponses, RemoveFeedPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/password',
    ...options
});

/**
 * Change a feed's password
 *
 * Needs the current password in `X-Feed-Password`. A feed can only get a password when it is created, so an open feed answers 409.
 */
export const changeFeedPassword = <ThrowOnError extends boolean = false>(options: Options<ChangeFeedPasswordData, ThrowOnError>): RequestResult<ChangeFeedPasswordResponses, ChangeFeedPasswordErrors, ThrowOnError> => (options.client ?? client).put<ChangeFeedPasswordResponses, ChangeFeedPasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/feeds/{feed}/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a feed's title and description by its read id
 *
 * Public, even on an instance with a password, and never reveals the feed's name. An unknown read id has an empty title and description, so read ids can't be probed.
 */
export const getReadFeed = <ThrowOnError extends boolean = false>(options: Options<GetReadFeedData, ThrowOnError>): RequestResult<GetReadFeedResponses, GetReadFeedErrors, ThrowOnError> => (options.client ?? client).get<GetReadFeedResponses, GetReadFeedErrors, ThrowOnError>({ url: '/api/v1/read/{readId}', ...options });

/**
 * List a feed's notes by its read id
 *
 * Public, even on an instance with a password, and never reveals the feed's name. An unknown read id is an empty list, so read ids can't be probed. The same notes as the read link's RSS.
 */
export const listReadNotes = <ThrowOnError extends boolean = false>(options: Options<ListReadNotesData, ThrowOnError>): RequestResult<ListReadNotesResponses, ListReadNotesErrors, ThrowOnError> => (options.client ?? client).get<ListReadNotesResponses, ListReadNotesErrors, ThrowOnError>({ url: '/api/v1/read/{readId}/notes', ...options });

/**
 * Get one note by its feed's read id
 *
 * Public, like the read link.
 */
export const getReadNote = <ThrowOnError extends boolean = false>(options: Options<GetReadNoteData, ThrowOnError>): RequestResult<GetReadNoteResponses, GetReadNoteErrors, ThrowOnError> => (options.client ?? client).get<GetReadNoteResponses, GetReadNoteErrors, ThrowOnError>({ url: '/api/v1/read/{readId}/notes/{id}', ...options });

/**
 * This API's OpenAPI document
 *
 * Generated from the server's route table, with `servers` set to this instance's URL.
 */
export const getOpenApi = <ThrowOnError extends boolean = false>(options?: Options<GetOpenApiData, ThrowOnError>): RequestResult<GetOpenApiResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOpenApiResponses, unknown, ThrowOnError>({ url: '/api/v1/openapi.json', ...options });
