// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://notefeed.me' | (string & {});
};

export type Note = {
    /**
     * The note's id: a UTC time to the second plus a random UUID for notes made here; any name without a dot for a file placed by hand
     */
    id: string;
    /**
     * The media type of the note's file: `text/markdown`, `image/png`, `image/jpeg`, `image/gif` or `image/webp`
     */
    type: string;
    /**
     * The note's file name, `<id>.<extension>`
     */
    file: string;
    /**
     * Where the note's file is served, absolute, under the feed's read id (public like the read link); null while the feed has no read link
     */
    file_url: string | null;
    /**
     * The size of the note's file in bytes
     */
    size: number;
    /**
     * The title set for the note, else the first heading or the first non-empty line of a markdown note, else the picture's alt text; may be empty
     */
    title: string;
    /**
     * The note's text, byte-for-byte as posted: for a text type (markdown) only; absent for a picture
     */
    content?: string;
    /**
     * Alternative text of an image note, when it has one
     */
    alt?: string;
    /**
     * The file name an image was posted with, when it came with one
     */
    name?: string;
    /**
     * When the note was posted (UTC)
     */
    created_at: string;
    /**
     * The note's page in the web UI
     */
    url: string;
    /**
     * Verified sign-in name of the poster; absent when the note was posted without a sign-in
     */
    sender?: string | null;
    /**
     * Labels the poster gave the note (not verified, and shown to readers like the note itself); empty when none
     */
    tags: Array<string>;
};

export type NoteList = {
    /**
     * Newest first
     */
    notes: Array<Note>;
    /**
     * Pass as `before` for the next (older) page; null on the last page
     */
    next: string | null;
};

export type Created = {
    id: string;
    /**
     * The note's page in the web UI
     */
    url: string;
    /**
     * The feed's page in the web UI
     */
    feed_url: string;
    /**
     * The feed's read-only RSS link, safe to share; null only if the server can't read the feed's stored read id, or if that id and the derived one both belong to other feeds
     */
    read_url: string | null;
    /**
     * The note's file name, `<id>.<extension>`. For an image note, pass it as a feed's `image` setting
     */
    file: string;
    /**
     * Where the note's file is served, absolute, under the feed's read id (public like the read link); null while the feed has no read link
     */
    file_url: string | null;
};

/**
 * The note the post is about: its text note, or with no `text` part its first picture
 */
export type Posted = {
    id: string;
    /**
     * The note's page in the web UI
     */
    url: string;
    /**
     * The feed's page in the web UI
     */
    feed_url: string;
    /**
     * The feed's read-only RSS link, safe to share; null only if the server can't read the feed's stored read id, or if that id and the derived one both belong to other feeds
     */
    read_url: string | null;
    /**
     * The note's file name, `<id>.<extension>`. For an image note, pass it as a feed's `image` setting
     */
    file: string;
    /**
     * Where the note's file is served, absolute, under the feed's read id (public like the read link); null while the feed has no read link
     */
    file_url: string | null;
    /**
     * A multipart request's pictures, one per `file` part, in their order; absent for a raw body
     */
    attachments?: Array<Created>;
};

export type NoteEdited = {
    /**
     * The note's id: a UTC time to the second plus a random UUID for notes made here; any name without a dot for a file placed by hand
     */
    id: string;
    /**
     * The media type of the note's file: `text/markdown`, `image/png`, `image/jpeg`, `image/gif` or `image/webp`
     */
    type: string;
    /**
     * The note's file name, `<id>.<extension>`
     */
    file: string;
    /**
     * Where the note's file is served, absolute, under the feed's read id (public like the read link); null while the feed has no read link
     */
    file_url: string | null;
    /**
     * The size of the note's file in bytes
     */
    size: number;
    /**
     * The title set for the note, else the first heading or the first non-empty line of a markdown note, else the picture's alt text; may be empty
     */
    title: string;
    /**
     * The note's text, byte-for-byte as posted: for a text type (markdown) only; absent for a picture
     */
    content?: string;
    /**
     * Alternative text of an image note, when it has one
     */
    alt?: string;
    /**
     * The file name an image was posted with, when it came with one
     */
    name?: string;
    /**
     * When the note was posted (UTC)
     */
    created_at: string;
    /**
     * The note's page in the web UI
     */
    url: string;
    /**
     * Verified sign-in name of the poster; absent when the note was posted without a sign-in
     */
    sender?: string | null;
    /**
     * Labels the poster gave the note (not verified, and shown to readers like the note itself); empty when none
     */
    tags: Array<string>;
    /**
     * A multipart request's pictures, one per `file` part, in their order; absent for a raw body
     */
    attachments?: Array<Created>;
};

export type MultipartNote = {
    /**
     * The markdown note (UTF-8): a field, or a file part (its name is ignored; its type, if any, `text/markdown` or `application/octet-stream`) to keep its line breaks as they are, since a form field's are sent as CRLF. At most one; required on a PUT. Its references to the files (`![](chart.png)`, `[x]: chart.png`) are swapped for the stored files; a file it never refers to is appended as `![](file)`
     */
    text?: string;
    /**
     * A picture: up to 10 parts, each with a file name (one path segment, 1 to 200 characters, unique in the request) and its image `Content-Type`. An `alt.<file name>` field gives one its alternative text
     */
    file?: Array<Blob | File>;
};

export type Error = {
    /**
     * A short reason, for people
     */
    error: string;
    /**
     * Stable machine-readable code; absent only on a 500
     */
    code?: 'invalid_feed' | 'reserved_feed' | 'auth' | 'rate_limited' | 'too_many_attempts' | 'feed_limit' | 'note_limit' | 'image_limit' | 'empty_note' | 'too_large' | 'unsupported_type' | 'invalid_body' | 'invalid_request' | 'not_found' | 'feed_exists' | 'taken';
};

export type NoteMeta = {
    /**
     * The note's title, at most 100 characters, one line; empty or left out means the title is taken from the text (a markdown note) or there is none (an image)
     */
    title?: string;
    /**
     * Alternative text of an image note, at most 500 characters, one line
     */
    alt?: string;
};

export type PasswordJson = {
    /**
     * The new password: 1 to 256 printable ASCII characters, with no space at the start or end
     */
    password: string;
};

export type FeedSettings = {
    /**
     * Display title, at most 100 characters, one line; empty means none (the feed's name is shown)
     */
    title: string;
    /**
     * Description, at most 500 characters, one line; may be empty
     */
    description: string;
    /**
     * The file name of an image uploaded to this feed (see uploadImage), shown as the feed's title image; empty removes it, omitted leaves it as it is
     */
    image?: string;
    /**
     * Whether readers (RSS, the read API and pages) see who posted each note; omitted leaves it as it is, a new feed starts with true
     */
    show_sender?: boolean;
    /**
     * A new read id (3 to 64 characters: a-z, 0-9, - and _), empty for a random one; omitted leaves it as it is. The old read link stops showing this feed, and may later show another one. Notes are not edited: a relative image link (`![](file)`) follows the new id, a full URL keeps the old one and is yours to change. Reserved feeds keep theirs. 409 when it is taken
     */
    read_id?: string;
};

export type Feed = {
    /**
     * The feed's name
     */
    name: string;
    /**
     * Display title, at most 100 characters, one line; empty means none (the feed's name is shown)
     */
    title: string;
    /**
     * Description, at most 500 characters, one line; may be empty
     */
    description: string;
    /**
     * Whether the feed has its own password
     */
    protected: boolean;
    /**
     * The feed's read-only RSS link; null while the feed has no notes, or if the server can't read the feed's stored read id
     */
    read_url: string | null;
    /**
     * The feed's title image (absolute URL, served under the read id), or null
     */
    image_url: string | null;
    /**
     * Whether readers see who posted each note
     */
    show_sender: boolean;
};

export type ReadFeed = {
    /**
     * Display title, at most 100 characters, one line; empty means none (the feed's name is shown)
     */
    title: string;
    /**
     * Description, at most 500 characters, one line; may be empty
     */
    description: string;
    /**
     * The feed's title image (absolute URL, served under the read id), or null
     */
    image_url: string | null;
};

export type ListNotesData = {
    body?: never;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: {
        /**
         * Notes per page, 1–100
         */
        limit?: number;
        /**
         * Only notes older than this id: the previous page's `next`
         */
        before?: string;
        /**
         * Only notes carrying this tag
         */
        tag?: string;
    };
    url: '/api/v1/feeds/{feed}/notes';
};

export type ListNotesErrors = {
    /**
     * Invalid or reserved feed name, or a bad `limit` / `before`
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * Too many wrong passwords from this client
     */
    429: Error;
};

export type ListNotesError = ListNotesErrors[keyof ListNotesErrors];

export type ListNotesResponses = {
    /**
     * A page of notes
     */
    200: NoteList;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type PostNoteData = {
    /**
     * The note, a file: its bytes, of the type `Content-Type` declares
     */
    body: Blob | File;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
        /**
         * The read id the feed gets when this post creates it: 3 to 64 characters (a-z, 0-9, - and _), random when left out or empty, ignored for a feed that exists. A short readable one is guessable: protect the feed with a password if that matters. 409 when it is taken
         */
        'X-Read-Id'?: string;
        /**
         * The note's title, for a raw body; a JSON or form body's own `title` wins. At most 100 characters, one line.
         */
        'X-Note-Title'?: string;
        /**
         * Tags for the note, comma-separated (`ci,deploy`): at most 10 tags, each 1 to 32 characters of letters, digits, `-`, `_`, `.` and `:`; case is folded to lowercase, duplicates are removed. For a raw markdown body; a JSON or form body's own `tags` wins. Empty is none.
         */
        'X-Note-Tags'?: string;
        /**
         * For an image body: its alternative text; a form's own `alt` wins.
         */
        'X-Note-Alt'?: string;
        /**
         * For an image body: the picture's original file name, kept with the note (at most 200 characters)
         */
        'X-Note-Name'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/notes';
};

export type PostNoteErrors = {
    /**
     * Invalid or reserved feed name; a blank note; a bad title, alt text or tags; a new password that is not printable ASCII; a multipart body with an unexpected part, no `text` and no `file`, more than 10 files, a bad or repeated file name, or `X-Note-Alt` / `X-Note-Name`
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * A password was sent for a feed that already exists without one: it can't be claimed; or the chosen read id is taken
     */
    409: Error;
    /**
     * Markdown over 102400 bytes, or an image over NOTEFEED_MAX_IMAGE_BYTES (each picture of a multipart body too), or a multipart body over 102400 bytes plus 10 images plus 64 KiB
     */
    413: Error;
    /**
     * Content-Type missing or not one of the accepted types, or the body (or a multipart body's picture) is not what it declares
     */
    415: Error;
    /**
     * Too many posts, or wrong passwords, from this client
     */
    429: Error;
    /**
     * NOTEFEED_MAX_FEEDS, NOTEFEED_MAX_NOTES_PER_FEED or NOTEFEED_MAX_IMAGES_PER_FEED reached
     */
    507: Error;
};

export type PostNoteError = PostNoteErrors[keyof PostNoteErrors];

export type PostNoteResponses = {
    /**
     * Stored: the note, and with a multipart body its pictures
     */
    201: Posted;
};

export type PostNoteResponse = PostNoteResponses[keyof PostNoteResponses];

export type DeleteNoteData = {
    body?: never;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
        /**
         * The note's id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/notes/{id}';
};

export type DeleteNoteErrors = {
    /**
     * Invalid or reserved feed name
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such note
     */
    404: Error;
    /**
     * Too many posts, edits and deletes, or wrong passwords, from this client
     */
    429: Error;
};

export type DeleteNoteError = DeleteNoteErrors[keyof DeleteNoteErrors];

export type DeleteNoteResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteNoteResponse = DeleteNoteResponses[keyof DeleteNoteResponses];

export type GetNoteData = {
    body?: never;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
        /**
         * The note's id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/notes/{id}';
};

export type GetNoteErrors = {
    /**
     * Invalid or reserved feed name
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such note
     */
    404: Error;
    /**
     * Too many wrong passwords from this client
     */
    429: Error;
};

export type GetNoteError = GetNoteErrors[keyof GetNoteErrors];

export type GetNoteResponses = {
    /**
     * The note
     */
    200: Note;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type PatchNoteData = {
    body: NoteMeta;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
        /**
         * The note's id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/notes/{id}';
};

export type PatchNoteErrors = {
    /**
     * Invalid or reserved feed name; nothing to change; a bad title or alt text; alt for a note that has none; bad JSON
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such note
     */
    404: Error;
    /**
     * Content-Type is not application/json
     */
    415: Error;
    /**
     * Too many posts, edits and deletes, or wrong passwords, from this client
     */
    429: Error;
};

export type PatchNoteError = PatchNoteErrors[keyof PatchNoteErrors];

export type PatchNoteResponses = {
    /**
     * The note as it is now
     */
    200: Note;
};

export type PatchNoteResponse = PatchNoteResponses[keyof PatchNoteResponses];

export type EditNoteData = {
    /**
     * The note, a file: its bytes, of the type `Content-Type` declares
     */
    body: Blob | File;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
        /**
         * Only for a multipart body: the tags go on the new pictures (the note keeps its own). A raw body ignores it. Comma-separated, empty is none.
         */
        'X-Note-Tags'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
        /**
         * The note's id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/notes/{id}';
};

export type EditNoteErrors = {
    /**
     * Invalid or reserved feed name; a blank note; a multipart body with an unexpected part, no `text`, more than 10 files, a bad or repeated file name, or `X-Note-Alt` / `X-Note-Name`
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such note
     */
    404: Error;
    /**
     * Markdown over 102400 bytes, or an image over NOTEFEED_MAX_IMAGE_BYTES (each picture of a multipart body too), or a multipart body over 102400 bytes plus 10 images plus 64 KiB
     */
    413: Error;
    /**
     * Content-Type missing, not accepted or not the note's own type (a multipart body is for a markdown note), or the body (or a picture) is not what it declares
     */
    415: Error;
    /**
     * Too many posts, edits and deletes, or wrong passwords, from this client
     */
    429: Error;
    /**
     * NOTEFEED_MAX_IMAGES_PER_FEED reached
     */
    507: Error;
};

export type EditNoteError = EditNoteErrors[keyof EditNoteErrors];

export type EditNoteResponses = {
    /**
     * The note as it is now, and with a multipart body the new pictures
     */
    200: NoteEdited;
};

export type EditNoteResponse = EditNoteResponses[keyof EditNoteResponses];

export type DeleteFeedData = {
    body?: never;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}';
};

export type DeleteFeedErrors = {
    /**
     * Invalid or reserved feed name
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such feed
     */
    404: Error;
    /**
     * Too many posts, edits and deletes, or wrong passwords, from this client
     */
    429: Error;
};

export type DeleteFeedError = DeleteFeedErrors[keyof DeleteFeedErrors];

export type DeleteFeedResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteFeedResponse = DeleteFeedResponses[keyof DeleteFeedResponses];

export type GetFeedData = {
    body?: never;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}';
};

export type GetFeedErrors = {
    /**
     * Invalid or reserved feed name
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such feed
     */
    404: Error;
    /**
     * Too many wrong passwords from this client
     */
    429: Error;
};

export type GetFeedError = GetFeedErrors[keyof GetFeedErrors];

export type GetFeedResponses = {
    /**
     * The feed
     */
    200: Feed;
};

export type GetFeedResponse = GetFeedResponses[keyof GetFeedResponses];

export type UpdateFeedData = {
    body: FeedSettings;
    headers?: {
        /**
         * The feed's own password, when it has one: to post, list or get, and (as the current password) to change or remove it. On the `POST` that creates a feed it sets the feed's password; on a `POST` to an existing feed that has none it answers 409. An empty value is the same as no header, so a `POST` with an empty one creates an open feed.
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}';
};

export type UpdateFeedErrors = {
    /**
     * Invalid or reserved feed name, bad JSON, a title or description that is too long or has control characters, a malformed read id, a reserved feed's read id, or chosen read ids turned off
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * No such feed
     */
    404: Error;
    /**
     * The read id belongs to another feed or is held back for a reserved one
     */
    409: Error;
    /**
     * Too many posts, edits and deletes, or wrong passwords, from this client
     */
    429: Error;
};

export type UpdateFeedError = UpdateFeedErrors[keyof UpdateFeedErrors];

export type UpdateFeedResponses = {
    /**
     * The feed as it is now
     */
    200: Feed;
};

export type UpdateFeedResponse = UpdateFeedResponses[keyof UpdateFeedResponses];

export type RemoveFeedPasswordData = {
    body?: never;
    headers?: {
        /**
         * The feed's current password
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/password';
};

export type RemoveFeedPasswordErrors = {
    /**
     * Invalid or reserved feed name
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * The feed has no password
     */
    409: Error;
    /**
     * Too many wrong passwords from this client
     */
    429: Error;
};

export type RemoveFeedPasswordError = RemoveFeedPasswordErrors[keyof RemoveFeedPasswordErrors];

export type RemoveFeedPasswordResponses = {
    /**
     * Removed
     */
    204: void;
};

export type RemoveFeedPasswordResponse = RemoveFeedPasswordResponses[keyof RemoveFeedPasswordResponses];

export type ChangeFeedPasswordData = {
    body: PasswordJson;
    headers?: {
        /**
         * The feed's current password
         */
        'X-Feed-Password'?: string;
    };
    path: {
        /**
         * The feed's name. It is the write key: anyone who knows it can post.
         */
        feed: string;
    };
    query?: never;
    url: '/api/v1/feeds/{feed}/password';
};

export type ChangeFeedPasswordErrors = {
    /**
     * Invalid or reserved feed name, bad JSON, or a new password that is not 1 to 256 printable ASCII characters, with no space at the start or end
     */
    400: Error;
    /**
     * The instance has a password, or the feed has its own, and it is missing or wrong
     */
    401: Error;
    /**
     * The feed has no password
     */
    409: Error;
    /**
     * Too many wrong passwords from this client
     */
    429: Error;
};

export type ChangeFeedPasswordError = ChangeFeedPasswordErrors[keyof ChangeFeedPasswordErrors];

export type ChangeFeedPasswordResponses = {
    /**
     * Changed; the old password and unlock cookies stop working
     */
    204: void;
};

export type ChangeFeedPasswordResponse = ChangeFeedPasswordResponses[keyof ChangeFeedPasswordResponses];

export type GetReadFeedData = {
    body?: never;
    path: {
        /**
         * The feed's read id, from its read link: 22 random characters, one the feed's owner chose, or the feed's own name for a reserved feed. Read-only; never reveals the name of any other feed.
         */
        readId: string;
    };
    query?: never;
    url: '/api/v1/read/{readId}';
};

export type GetReadFeedErrors = {
    /**
     * Malformed read id
     */
    404: Error;
};

export type GetReadFeedError = GetReadFeedErrors[keyof GetReadFeedErrors];

export type GetReadFeedResponses = {
    /**
     * The feed's public settings
     */
    200: ReadFeed;
};

export type GetReadFeedResponse = GetReadFeedResponses[keyof GetReadFeedResponses];

export type ListReadNotesData = {
    body?: never;
    path: {
        /**
         * The feed's read id, from its read link: 22 random characters, one the feed's owner chose, or the feed's own name for a reserved feed. Read-only; never reveals the name of any other feed.
         */
        readId: string;
    };
    query?: {
        /**
         * Notes per page, 1–100
         */
        limit?: number;
        /**
         * Only notes older than this id: the previous page's `next`
         */
        before?: string;
        /**
         * Only notes carrying this tag
         */
        tag?: string;
    };
    url: '/api/v1/read/{readId}/notes';
};

export type ListReadNotesErrors = {
    /**
     * A bad `limit` / `before`
     */
    400: Error;
    /**
     * Malformed read id
     */
    404: Error;
};

export type ListReadNotesError = ListReadNotesErrors[keyof ListReadNotesErrors];

export type ListReadNotesResponses = {
    /**
     * A page of notes
     */
    200: NoteList;
};

export type ListReadNotesResponse = ListReadNotesResponses[keyof ListReadNotesResponses];

export type GetReadNoteData = {
    body?: never;
    path: {
        /**
         * The feed's read id, from its read link: 22 random characters, one the feed's owner chose, or the feed's own name for a reserved feed. Read-only; never reveals the name of any other feed.
         */
        readId: string;
        /**
         * The note's id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/read/{readId}/notes/{id}';
};

export type GetReadNoteErrors = {
    /**
     * No such note, or a malformed or unknown read id
     */
    404: Error;
};

export type GetReadNoteError = GetReadNoteErrors[keyof GetReadNoteErrors];

export type GetReadNoteResponses = {
    /**
     * The note
     */
    200: Note;
};

export type GetReadNoteResponse = GetReadNoteResponses[keyof GetReadNoteResponses];

export type GetOpenApiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/openapi.json';
};

export type GetOpenApiResponses = {
    /**
     * OpenAPI 3.1
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOpenApiResponse = GetOpenApiResponses[keyof GetOpenApiResponses];
